# Generated by Django 5.2.2 on 2025-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inclusao_alimentacao",
            "0039_quantidadedealunosemeiinclusaodealimentacaocemei_tipos_alimentacao",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quantidadedealunosemeiinclusaodealimentacaocemei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quantidadedealunosporfaixaetariadainclusaodealimentacaocemei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quantidadedealunosporfaixaetariadainclusaodealimentacaodacei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
