# Generated by Django 5.2.13 on 2026-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inclusao_alimentacao",
            "0040_alter_quantidadedealunosemeiinclusaodealimentacaocemei_matriculados_quando_criado_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quantidadeporperiodo",
            name="encerrado_a_partir_de",
            field=models.DateField(
                blank=True,
                help_text="Data a partir da qual essa quantidade por período não é mais válida; todo o período entre data_inicial e esta data continua autorizado e foi fornecido pela empresa.",
                null=True,
            ),
        ),
    ]
