# Generated by Django 4.2.7 on 2025-02-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terceirizada", "0023_alter_contrato_modalidade"),
        ("escola", "0072_alunoperiodoparcial_data_removido"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diasuspensaoatividades",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="diasuspensaoatividades",
            name="edital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="terceirizada.edital",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="diasuspensaoatividades",
            unique_together={("tipo_unidade", "data", "edital")},
        ),
    ]
