# Generated by Django 4.2.7 on 2025-03-06 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0073_alter_diasuspensaoatividades_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="historicomatriculaaluno",
            unique_together=set(),
        ),
    ]
