# Generated by Django 5.2.2 on 2025-07-25 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0074_alter_historicomatriculaaluno_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faixaetaria",
            name="fim",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="faixaetaria",
            name="inicio",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
