# Generated by Django 5.2.2 on 2025-12-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0076_auto_20251017_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="diacalendario",
            name="periodo_escolar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dias_calendario",
                to="escola.periodoescolar",
            ),
        ),
    ]
