# Generated by Django 5.2.9 on 2026-02-02 15:06

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


def cria_historico_escolas_cemei(apps, _):
    HistoricoEscola = apps.get_model("escola", "HistoricoEscola")
    Escola = apps.get_model("escola", "Escola")
    TipoUnidadeEscolar = apps.get_model("escola", "TipoUnidadeEscolar")

    emei = TipoUnidadeEscolar.objects.filter(iniciais="EMEI").first()
    if not emei:
        return
    data_final = datetime.date(2025, 12, 31)

    escola_cemei_caminho_dos_martins = Escola.objects.filter(
        codigo_eol="019533"
    ).first()
    if escola_cemei_caminho_dos_martins:
        HistoricoEscola.objects.update_or_create(
            escola=escola_cemei_caminho_dos_martins,
            nome="EMEI CAMINHO DOS MARTINS",
            tipo_unidade=emei,
            data_final=data_final,
        )

    escola_cemei_anita_costa = Escola.objects.filter(codigo_eol="092380").first()
    if escola_cemei_anita_costa:
        HistoricoEscola.objects.update_or_create(
            escola=escola_cemei_anita_costa,
            nome="EMEI ANITA COSTA, DA.",
            tipo_unidade=emei,
            data_final=data_final,
        )


def backwards(apps, _):
    HistoricoEscola = apps.get_model("escola", "HistoricoEscola")
    HistoricoEscola.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0077_diacalendario_periodo_escolar"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoEscola",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data_inicial", models.DateField(null=True)),
                ("data_final", models.DateField(null=True)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_escola",
                        to="escola.escola",
                    ),
                ),
                (
                    "tipo_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escola.tipounidadeescolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico da Escola",
                "verbose_name_plural": "Históricos da escola",
            },
        ),
        migrations.RunPython(cria_historico_escolas_cemei, backwards),
    ]
