# Generated by Django 5.2.13 on 2026-04-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0079_alter_historicoescola_data_inicial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escola",
            name="tipos_contagem",
        ),
    ]
