# Generated by Django 5.2.13 on 2026-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0080_remove_escola_tipos_contagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipounidadeescolar",
            name="cardapios",
        ),
    ]
