# Generated by Django 5.2.13 on 2026-06-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0081_remove_tipounidadeescolar_cardapios"),
        ("medicao_inicial", "0066_alter_responsavel_rf"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alunoperiodoparcial",
            unique_together={("escola", "aluno", "solicitacao_medicao_inicial")},
        ),
    ]
