# Generated by Django 5.2.14 on 2026-06-17 17:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0082_alter_alunoperiodoparcial_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaLetivoSIGPAE",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escolas",
                    models.ManyToManyField(
                        related_name="dias_letivos_sigpae", to="escola.escola"
                    ),
                ),
                (
                    "lotes",
                    models.ManyToManyField(
                        related_name="dias_letivos_sigpae", to="escola.lote"
                    ),
                ),
                (
                    "periodos_escolares",
                    models.ManyToManyField(
                        related_name="dias_letivos_sigpae", to="escola.periodoescolar"
                    ),
                ),
                (
                    "tipos_unidade_escolar",
                    models.ManyToManyField(
                        related_name="dias_letivos_sigpae",
                        to="escola.tipounidadeescolar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dia letivo no SIGPAE",
                "verbose_name_plural": "Dias letivos no SIGPAE",
            },
        ),
    ]
