# Generated by Django 5.2.15 on 2026-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0083_dialetivosigpae"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escola",
            name="acesso_desde",
            field=models.DateField(
                blank=True,
                help_text="Define o mês a partir do qual a escola poderá realizar o lançamento da medição inicial.",
                null=True,
                verbose_name="Acesso módulo medição desde",
            ),
        ),
    ]
