# Generated by Django 5.2.11 on 2026-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0083_alter_produtoedital_suspenso_justificativa"),
    ]

    operations = [
        migrations.AddField(
            model_name="informacaonutricional",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Está ativo?"),
        ),
    ]
