# Generated by Django 5.2.17 on 2026-08-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0084_informacaonutricional_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtoedital",
            name="suspenso_justificativa",
            field=models.TextField(
                blank=True, verbose_name="Porque foi suspenso individualmente"
            ),
        ),
    ]
