# Generated by Django 5.2.17 on 2026-09-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados_comuns", "0137_alter_logsolicitacoesusuario_status_evento"),
        ("produto", "0085_alter_produtoedital_suspenso_justificativa"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosHistoricosProduto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto_uuid", models.UUIDField()),
                ("empresa", models.CharField(blank=True, max_length=255)),
                ("criado_em_produto", models.DateTimeField(blank=True, null=True)),
                ("nome_produto", models.CharField(max_length=255)),
                ("marca", models.CharField(blank=True, max_length=255)),
                ("fabricante", models.CharField(blank=True, max_length=255)),
                ("eh_para_alunos_com_dieta", models.BooleanField(default=False)),
                ("componentes", models.TextField(blank=True)),
                ("perfil_responsavel", models.CharField(blank=True, max_length=100)),
                ("nome_instituicao", models.CharField(blank=True, max_length=255)),
                (
                    "log",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados_produto",
                        to="dados_comuns.logsolicitacoesusuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dados históricos do produto",
                "verbose_name_plural": "Dados históricos dos produtos",
            },
        ),
    ]
