# Generated by Django 4.2.7 on 2025-04-01 16:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recebimento", "0005_fichaderecebimento_observacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestaoFichaRecebimento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "resposta",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Resposta (Sim/Não)"
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recebimento.fichaderecebimento",
                        verbose_name="Ficha de Recebimento",
                    ),
                ),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recebimento.questaoconferencia",
                        verbose_name="Questão de Conferência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questão por Ficha de Recebimento",
                "verbose_name_plural": "Questões por Fichas de Recebimento",
                "unique_together": {("ficha", "questao")},
            },
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="questoes_conferencia",
            field=models.ManyToManyField(
                related_name="fichas_vinculadas",
                through="recebimento.QuestaoFichaRecebimento",
                to="recebimento.questaoconferencia",
            ),
        ),
    ]
