# Generated by Django 4.2.7 on 2025-04-01 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recebimento", "0006_questaoficharecebimento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questaoficharecebimento",
            old_name="ficha",
            new_name="ficha_recebimento",
        ),
        migrations.RenameField(
            model_name="questaoficharecebimento",
            old_name="questao",
            new_name="questao_conferencia",
        ),
        migrations.AlterUniqueTogether(
            name="questaoficharecebimento",
            unique_together={("ficha_recebimento", "questao_conferencia")},
        ),
    ]
