# Generated by Django 4.2.7 on 2025-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recebimento", "0008_fichaderecebimento_observacoes_conferencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="questaoficharecebimento",
            name="tipo_questao",
            field=models.CharField(
                choices=[("PRIMARIA", "Primária"), ("SECUNDARIA", "Secundária")],
                default="PRIMARIA",
            ),
            preserve_default=False,
        ),
    ]
