# Generated by Django 5.2.2 on 2025-07-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0011_ocorrenciaficharecebimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrenciaficharecebimento",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
    ]
