# Generated by Django 5.2.2 on 2025-09-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0013_fichaderecebimento_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaderecebimento",
            name="houve_ocorrencia",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Houve Ocorrência?"
            ),
        ),
    ]
