# Generated by Django 5.2.2 on 2025-10-03 10:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0015_alter_fichaderecebimento_numero_paletes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReposicaoCronogramaFichaRecebimento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("R", "Repor os produtos faltantes/recusados"),
                            ("C", "Fazer uma carta de crédito do valor pago"),
                            ("O", "Outros"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Referência de Ocorrência da Ficha de Recebimento",
                "verbose_name_plural": "Referências de Ocorrências das Fichas de Recebimento",
                "ordering": ["criado_em"],
            },
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="reposicao_cronograma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reposicao_cronograma",
                to="recebimento.reposicaocronogramaficharecebimento",
            ),
        ),
    ]
