# Generated by Django 5.2.2 on 2025-10-03 17:04

from django.db import migrations, models


def cria_reposicao(apps, schema_editor):
    ReposicaoCronogramaFichaRecebimento = apps.get_model(
        "recebimento", "ReposicaoCronogramaFichaRecebimento"
    )

    ReposicaoCronogramaFichaRecebimento.objects.get_or_create(
        tipo="Repor", descricao="REPOR OS PRODUTOS FALTANTES/RECUSADOS"
    )
    ReposicaoCronogramaFichaRecebimento.objects.get_or_create(
        tipo="Credito", descricao="FAZER UMA CARTA DE CRÉDITO DO VALOR PAGO"
    )


def remove_reposicao(apps, schema_editor):
    ReposicaoCronogramaFichaRecebimento = apps.get_model(
        "recebimento", "ReposicaoCronogramaFichaRecebimento"
    )
    ReposicaoCronogramaFichaRecebimento.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0016_reposicaocronogramaficharecebimento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reposicaocronogramaficharecebimento",
            options={
                "ordering": ["criado_em"],
                "verbose_name": "Reposição Cronograma da Ficha de Recebimento",
                "verbose_name_plural": "Reposições Cronogramas das Fichas de Recebimento",
            },
        ),
        migrations.AlterField(
            model_name="reposicaocronogramaficharecebimento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Repor", "Repor os produtos faltantes/recusados"),
                    ("Credito", "Fazer uma carta de crédito do valor pago"),
                    ("Outros", "Outros"),
                ],
                max_length=7,
                verbose_name="Tipo",
            ),
        ),
        migrations.RunPython(cria_reposicao, reverse_code=remove_reposicao),
    ]
