# Generated by Django 5.2.2 on 2025-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0019_fichaderecebimento_documentos_recebimento_novo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentofichaderecebimento",
            name="quantidade_recebida",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantidade recebida do documento",
                max_digits=10,
                null=True,
                verbose_name="Quantidade Recebida",
            ),
        ),
    ]
