# Generated by Django 5.2.2 on 2025-10-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0021_migrate_data_documentos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaderecebimento",
            name="documentos_recebimento",
        ),
    ]
