# Generated by Django 5.2.2 on 2025-10-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0075_alter_etapasdocronograma_options_and_more"),
        ("recebimento", "0022_remove_fichaderecebimento_documentos_recebimento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichaderecebimento",
            name="documentos_recebimento_novo",
        ),
        migrations.AddField(
            model_name="fichaderecebimento",
            name="documentos_recebimento",
            field=models.ManyToManyField(
                related_name="fichas_recebimentos",
                through="recebimento.DocumentoFichaDeRecebimento",
                through_fields=("ficha_recebimento", "documento_recebimento"),
                to="pre_recebimento.documentoderecebimento",
            ),
        ),
    ]
