# Generated by Django 5.2.2 on 2025-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recebimento",
            "0023_remove_fichaderecebimento_documentos_recebimento_novo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentofichaderecebimento",
            name="quantidade_recebida",
            field=models.IntegerField(
                blank=True,
                help_text="Quantidade recebida do documento",
                null=True,
                verbose_name="Quantidade Recebida",
            ),
        ),
    ]
