# Generated by Django 5.2.13 on 2026-06-19 18:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0090_alter_cronogramasemanal_status"),
        (
            "recebimento",
            "0026_alter_veiculofichaderecebimento_embalagens_nota_fiscal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AjusteSaldo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "quantidade_descontada",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "documento_recebimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajustes_saldo",
                        to="pre_recebimento.documentoderecebimento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
