# Generated by Django 4.2.7 on 2025-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recebimento",
            "0007_rename_ficha_questaoficharecebimento_ficha_recebimento_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaderecebimento",
            name="observacoes_conferencia",
            field=models.TextField(blank=True, null=True),
        ),
    ]
