# Generated by Django 4.2.7 on 2025-04-14 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recebimento", "0009_questaoficharecebimento_tipo_questao"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questaoficharecebimento",
            unique_together={
                ("ficha_recebimento", "questao_conferencia", "tipo_questao")
            },
        ),
    ]
