# Generated by Django 5.2.2 on 2025-08-11 15:55

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0012_alter_ocorrenciaficharecebimento_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichaderecebimento",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=16,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="RASCUNHO",
                    name="FichaDeRecebimentoWorkflow",
                    states=["RASCUNHO", "ASSINADA"],
                ),
            ),
        ),
    ]
