# Generated by Django 5.2.2 on 2025-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0016_reposicaocronogramaficharecebimento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reposicaocronogramaficharecebimento",
            options={
                "ordering": ["criado_em"],
                "verbose_name": "Reposição Cronograma da Ficha de Recebimento",
                "verbose_name_plural": "Reposições Cronogramas das Fichas de Recebimento",
            },
        ),
        migrations.AlterField(
            model_name="reposicaocronogramaficharecebimento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Repor", "Repor os produtos faltantes/recusados"),
                    ("Credito", "Fazer uma carta de crédito do valor pago"),
                    ("Outros", "Outros"),
                ],
                max_length=7,
                verbose_name="Tipo",
            ),
        ),
    ]
