# Generated by Django 5.2.2 on 2025-10-15 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0075_alter_etapasdocronograma_options_and_more"),
        (
            "recebimento",
            "0017_alter_reposicaocronogramaficharecebimento_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoFichaDeRecebimento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "quantidade_recebida",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantidade recebida do documento",
                        max_digits=10,
                        verbose_name="Quantidade Recebida",
                    ),
                ),
                (
                    "documento_recebimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichas_documentos",
                        to="pre_recebimento.documentoderecebimento",
                        verbose_name="Documento de Recebimento",
                    ),
                ),
                (
                    "ficha_recebimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_ficha",
                        to="recebimento.fichaderecebimento",
                        verbose_name="Ficha de Recebimento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Ficha de Recebimento",
                "verbose_name_plural": "Documentos Fichas de Recebimento",
                "unique_together": {("ficha_recebimento", "documento_recebimento")},
            },
        ),
    ]
