# Generated by Django 5.2.2 on 2025-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0024_alter_documentofichaderecebimento_quantidade_recebida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentofichaderecebimento",
            name="quantidade_recebida",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantidade recebida do documento",
                max_digits=15,
                null=True,
                verbose_name="Quantidade Recebida",
            ),
        ),
    ]
