# Generated by Django 5.2.2 on 2026-01-13 14:46
import re
from django.db import migrations, models
from decimal import Decimal, InvalidOperation


def limpar_campos_numericos(apps, _):
    Veiculo = apps.get_model("recebimento", "VeiculoFichaDeRecebimento")

    for obj in Veiculo.objects.all():
        if obj.quantidade_nota_fiscal:
            try:
                valor = str(obj.quantidade_nota_fiscal).replace(",", ".")
                obj.quantidade_nota_fiscal = Decimal(valor)
            except (InvalidOperation, ValueError):
                obj.quantidade_nota_fiscal = None

        if obj.quantidade_recebida:
            try:
                valor = str(obj.quantidade_recebida).replace(",", ".")
                obj.quantidade_recebida = Decimal(valor)
            except (InvalidOperation, ValueError):
                obj.quantidade_recebida = None

        if obj.embalagens_nota_fiscal:
            if re.match(r"^\d+$", str(obj.embalagens_nota_fiscal)):
                obj.embalagens_nota_fiscal = int(obj.embalagens_nota_fiscal)
            else:
                obj.embalagens_nota_fiscal = None

        if obj.embalagens_recebidas:
            if re.match(r"^\d+$", str(obj.embalagens_recebidas)):
                obj.embalagens_recebidas = int(obj.embalagens_recebidas)
            else:
                obj.embalagens_recebidas = None

        obj.save(update_fields=[
            "quantidade_nota_fiscal",
            "quantidade_recebida",
            "embalagens_nota_fiscal",
            "embalagens_recebidas",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0025_alter_documentofichaderecebimento_quantidade_recebida"),
    ]

    operations = [
        migrations.RunPython(limpar_campos_numericos),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="embalagens_nota_fiscal",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Quantidade de Embalagens da Nota Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="embalagens_recebidas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de Embalagens Recebidas"
            ),
        ),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="quantidade_nota_fiscal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="quantidade_recebida",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
