# Generated by Django 5.2.2 on 2026-01-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recebimento", "0025_alter_documentofichaderecebimento_quantidade_recebida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="embalagens_nota_fiscal",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Quantidade de Embalagens da Nota Fiscal",
            ),
        ),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="embalagens_recebidas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de Embalagens Recebidas"
            ),
        ),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="quantidade_nota_fiscal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="veiculofichaderecebimento",
            name="quantidade_recebida",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
