language: python
services:
  - postgresql
  - redis-server
python:
  - "3.8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'adminadmin';" -U postgres
  - psql -c "ALTER USER admin CREATEDB;" -U postgres
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"

install:
  - pip install pipenv==2022.4.8
  - pipenv install --dev
script:
  - pytest
  - flake8
  - bandit -r sme_terceirizadas -ll
#TODO: com grafana ta dando bug. verificar ExportModelOperationsMixin
#  - mypy sme_terceirizadas
  - bash utility/verifica_import_relativo.sh
  - isort --check-only sme_terceirizadas
  - docker build -t marcelomaia/terceirizadas_backend .
  - docker run -d -p 8000:8000 marcelomaia/terceirizadas_backend python manage.py runserver --settings=config.settings.local
  - docker ps -a
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash utility/telegram_notification.sh

deploy:
  provider: script
  script: bash utility/deploy_dockerhub.sh
  on:
    all_branches: true
