version: "3.1"

services:
  db:
    image: postgres:12.17-alpine
    container_name: db-sigpae
    env_file: .env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5.0.0-alpine
    container_name: redis-sigpae
    ports:
      - 6379:6379
    restart: always
