# Generated by Django 2.2.13 on 2023-01-11 14:29

import django.core.validators
from django.db import migrations, models


def popular_posicao(apps, _):
    tipo_alimentacao = apps.get_model("cardapio", "TipoAlimentacao")
    tipo_alimentacao.objects.filter(nome="Lanche 4h").update(posicao=1)
    tipo_alimentacao.objects.filter(nome="Lanche").update(posicao=2)
    tipo_alimentacao.objects.filter(nome="Refeição").update(posicao=3)
    tipo_alimentacao.objects.filter(nome="Sobremesa").update(posicao=4)


def backwards(apps, _):
    tipo_alimentacao = apps.get_model("cardapio", "TipoAlimentacao")
    tipo_alimentacao.objects.update(posicao=None)


class Migration(migrations.Migration):
    dependencies = [
        ("cardapio", "0041_auto_20221221_1140"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoalimentacao",
            name="posicao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.RunPython(popular_posicao, backwards),
    ]
