# Generated by Django 5.2.13 on 2026-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0051_remove_alteracao_cardapio_lanche_repetida"),
        ("escola", "0081_remove_tipounidadeescolar_cardapios"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inversaocardapio",
            name="cardapio_para",
        ),
        migrations.RemoveField(
            model_name="inversaocardapio",
            name="cardapio_de",
        ),
        migrations.DeleteModel(
            name="Cardapio",
        ),
    ]
