# Generated by Django 4.2.7 on 2025-03-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0074_alter_historicomatriculaaluno_unique_together"),
        (
            "dieta_especial",
            "0059_logquantidadedietasautorizadas_infantil_ou_fundamental",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="logquantidadedietasautorizadascei",
            name="faixa_etaria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="escola.faixaetaria",
            ),
        ),
    ]
