# Generated by Django 5.2.1 on 2025-06-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dieta_especial", "0060_alter_logquantidadedietasautorizadascei_faixa_etaria"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaodietaespecial",
            name="dieta_para_recreio_ferias",
            field=models.BooleanField(
                default=False, verbose_name="Dieta para Recreio nas Férias"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaodietaespecial",
            name="periodo_recreio_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Período do Recreio - Até"
            ),
        ),
        migrations.AddField(
            model_name="solicitacaodietaespecial",
            name="periodo_recreio_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Período do Recreio - De"
            ),
        ),
    ]
