# Generated by Django 5.2.13 on 2026-04-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dieta_especial", "0066_delete_arquivocargausuariosescola"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AlimentoProprio",
        ),
    ]
