# Generated by Django 5.2.2 on 2025-10-17 16:52

from django.db import migrations


def criar_grupo_seis_com_tipos_unidade(apps, schema_editor):
    # Obtém os modelos usando o histórico
    GrupoUnidadeEscolar = apps.get_model('escola', 'GrupoUnidadeEscolar')
    TipoUnidadeEscolar = apps.get_model('escola', 'TipoUnidadeEscolar')
    try:
        cieja = TipoUnidadeEscolar.objects.get(iniciais="CIEJA")
        cmct = TipoUnidadeEscolar.objects.get(iniciais="CMCT")
        # Remove CIEJA do grupo 4
        grupo_quatro = GrupoUnidadeEscolar.objects.get(nome="Grupo 4")
        if grupo_quatro.tipos_unidades.filter(iniciais="CIEJA").exists():
            grupo_quatro.tipos_unidades.remove(cieja)
        # Cria o Grupo 6 e Adiciona CIEJA e CMCT ao grupo
        grupo_seis, created = GrupoUnidadeEscolar.objects.get_or_create(
            nome="Grupo 6",
            defaults={'nome': "Grupo 6"}
        )
        grupo_seis.tipos_unidades.add(cieja, cmct)
    except Exception as e:
        print(f"Erro no método criar_grupo_seis_com_tipos_unidade: {e}")


def remover_grupo_seis_restaurar_estado_anterior(apps, schema_editor):
    # Obtém os modelos usando o histórico
    GrupoUnidadeEscolar = apps.get_model('escola', 'GrupoUnidadeEscolar')
    TipoUnidadeEscolar = apps.get_model('escola', 'TipoUnidadeEscolar')
    try:
        cieja = TipoUnidadeEscolar.objects.get(iniciais="CIEJA")
        cmct = TipoUnidadeEscolar.objects.get(iniciais="CMCT")
        # Remove CIEJA e CMCT do Grupo 6
        grupo_seis = GrupoUnidadeEscolar.objects.get(nome="Grupo 6")
        grupo_seis.tipos_unidades.remove(cieja, cmct)
        # Adiciona CIEJA de volta ao Grupo 4
        grupo_quatro = GrupoUnidadeEscolar.objects.get(nome="Grupo 4")
        if not grupo_quatro.tipos_unidades.filter(iniciais="CIEJA").exists():
            grupo_quatro.tipos_unidades.add(cieja)
        # Deleta o Grupo 6
        grupo_seis.delete()
    except Exception as e:
        print(f"Erro no método remover_grupo_seis_restaurar_estado_anterior: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0075_alter_faixaetaria_fim_alter_faixaetaria_inicio"),
    ]

    operations = [
        migrations.RunPython(
            criar_grupo_seis_com_tipos_unidade,
            remover_grupo_seis_restaurar_estado_anterior
        ),
    ]
