# Generated by Django 5.2.11 on 2026-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0078_historicoescola"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicoescola",
            name="data_inicial",
            field=models.DateField(blank=True, null=True),
        ),
    ]
