# Generated by Django 2.2.10 on 2020-06-18 18:39

import django.db.models.deletion
from django.db import migrations, models

from src.dados_comuns.prometheus_mixin import ExportModelOperationsMixin


class Migration(migrations.Migration):
    dependencies = [
        ("dados_comuns", "0013_auto_20200526_1641"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoLogSolicitacoesUsuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=255)),
                ("arquivo", models.FileField(upload_to="")),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="anexos",
                        to="dados_comuns.LogSolicitacoesUsuario",
                    ),
                ),
            ],
            bases=(
                ExportModelOperationsMixin("log_solicitacoes_anexo"),
                models.Model,
            ),
        ),
    ]
