# Generated by Django 5.2.13 on 2026-08-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dados_comuns", "0134_versaosistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perguntafrequente",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dados_comuns.categoriaperguntafrequente",
            ),
        ),
    ]
