# Generated by Django 5.2.14 on 2026-08-18 13:54

import django.db.models.deletion
from django.db import migrations, models


def disponibilizar_duvidas_existentes_para_todos(apps, schema_editor):
    PerguntaFrequente = apps.get_model("dados_comuns", "PerguntaFrequente")
    PerguntaFrequente.objects.update(todos_os_perfis=True)


class Migration(migrations.Migration):

    dependencies = [
        ("dados_comuns", "0134_versaosistema"),
        ("perfil", "0023_usuario_aceitou_termos"),
    ]

    operations = [
        migrations.AddField(
            model_name="perguntafrequente",
            name="perfis",
            field=models.ManyToManyField(
                blank=True, related_name="perguntas_frequentes", to="perfil.perfil"
            ),
        ),
        migrations.AddField(
            model_name="perguntafrequente",
            name="todos_os_perfis",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            disponibilizar_duvidas_existentes_para_todos,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="perguntafrequente",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dados_comuns.categoriaperguntafrequente",
            ),
        ),
    ]
