# Generated by Django 5.2.2 on 2025-11-10 15:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


def cria_tipo(apps, _):
    TipoValorParametrizacaoFinanceira = apps.get_model(
        "medicao_inicial", "TipoValorParametrizacaoFinanceira"
    )
    TipoValorParametrizacaoFinanceira.objects.get_or_create(nome="UNITARIO")
    TipoValorParametrizacaoFinanceira.objects.get_or_create(nome="REAJUSTE")
    TipoValorParametrizacaoFinanceira.objects.get_or_create(nome="ACRESCIMO")


def remove_tipo(apps, _):
    TipoValorParametrizacaoFinanceira = apps.get_model(
        "medicao_inicial", "TipoValorParametrizacaoFinanceira"
    )
    TipoValorParametrizacaoFinanceira.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0048_alter_parametrizacaofinanceiratabela_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoValorParametrizacaoFinanceira",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="tipo_valor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametrizacao_tipo_valor",
                to="medicao_inicial.tipovalorparametrizacaofinanceira",
            ),
        ),
        migrations.RunPython(cria_tipo, reverse_code=remove_tipo),
    ]
