# Generated by Django 5.2.2 on 2025-11-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0050_alter_parametrizacaofinanceiratabelavalor_nome_campo",
        ),
        ("medicao_inicial", "0051_recreionasferiasunidadeparticipante_cei_ou_emei"),
    ]

    operations = []
