# Generated by Django 5.2.8 on 2025-12-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0054_alter_ocorrenciamedicaoinicial_nome_ultimo_arquivo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recreionasferias",
            options={"ordering": ["-alterado_em"]},
        ),
    ]
