# Generated by Django 5.2.8 on 2025-12-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0055_alter_recreionasferias_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="recreio_nas_ferias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitacoes_medicao_inicial",
                to="medicao_inicial.recreionasferias",
            ),
        ),
    ]
