# Generated by Django 5.2.8 on 2025-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0055_alter_recreionasferias_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="eh_recreio_nas_ferias",
            field=models.BooleanField(default=False),
        ),
    ]
