# Generated by Django 5.2.2 on 2026-03-23 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0079_alter_historicoescola_data_inicial"),
        ("medicao_inicial", "0061_lancheemergencialdiario_criado_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosLiquidacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "numero_empenho",
                    models.CharField(max_length=40, verbose_name="Número do empenho"),
                ),
                (
                    "tipo_empenho",
                    models.CharField(max_length=100, verbose_name="Tipo de empenho"),
                ),
                (
                    "relatorio_financeiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dados_liquidacao",
                        to="medicao_inicial.relatoriofinanceiro",
                        to_field="uuid",
                    ),
                ),
                (
                    "unidades_educacionais",
                    models.ManyToManyField(
                        blank=True, related_name="dados_liquidacao", to="escola.escola"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dado Liquidação",
                "verbose_name_plural": "Dados Liquidações",
                "ordering": ["-alterado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "numero_empenho",
                            "tipo_empenho",
                            "relatorio_financeiro",
                        ),
                        name="unique_dados_liquidacao_empenho_por_relatorio",
                    )
                ],
            },
        ),
    ]
