# Generated by Django 5.2.13 on 2026-04-15 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import sme_sigpae_api.dados_comuns.behaviors


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0080_remove_escola_tipos_contagem"),
        ("medicao_inicial", "0062_dadosliquidacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAcessoMedicaoInicialUE",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data_inicial", models.DateField(verbose_name="Data inicial")),
                (
                    "data_final",
                    models.DateField(blank=True, null=True, verbose_name="Data final"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos_acesso_medicao_inicial_ue",
                        to="escola.escola",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos_acesso_medicao_inicial_ue",
                        to="escola.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de acesso à medição inicial da UE",
                "verbose_name_plural": "Históricos de acesso à medição inicial da UE",
            },
            bases=(
                sme_sigpae_api.dados_comuns.behaviors.TemIdentificadorExternoAmigavel,
                models.Model,
            ),
        ),
    ]
