# Generated by Django 5.2.13 on 2026-04-27 15:13

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0063_historicoacessomedicaoinicialue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatoriofinanceiro",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=27,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="RELATORIO_FINANCEIRO_GERADO",
                    name="RelatorioFinanceiroMedicaoInicialWorkflow",
                    states=[
                        "RELATORIO_FINANCEIRO_GERADO",
                        "EM_ANALISE",
                        "GERADA_MEDICAO_FINAL",
                        "FINALIZADO",
                    ],
                ),
            ),
        ),
    ]
