# Generated by Django 4.2.7 on 2025-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0059_cronograma_observacoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="porcao",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Porção"
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="valor_unidade_caseira",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Unidade Caseira"
            ),
        ),
    ]
