# Generated by Django 5.2.1 on 2025-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pre_recebimento",
            "0071_alter_fichatecnicadoproduto_envasador_distribuidor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analisefichatecnica",
            name="fabricante_envasador_conferido",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="analisefichatecnica",
            name="fabricante_envasador_correcoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analisefichatecnica",
            name="modo_preparo_correcoes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="analisefichatecnica",
            name="responsavel_tecnico_correcoes",
            field=models.TextField(blank=True),
        ),
    ]
