# Generated by Django 5.2.2 on 2025-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0074_rename_parte_new_and_remove_parte_old"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etapasdocronograma",
            options={
                "ordering": ["etapa", "parte"],
                "verbose_name": "Etapa do Cronograma",
                "verbose_name_plural": "Etapas dos Cronogramas",
            },
        ),
        migrations.AddIndex(
            model_name="etapasdocronograma",
            index=models.Index(
                fields=["etapa", "parte"], name="pre_recebim_etapa_d3b480_idx"
            ),
        ),
    ]
