# Generated by Django 5.2.2 on 2025-11-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pre_recebimento",
            "0076_alter_documentoderecebimento_quantidade_laudo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentoderecebimento",
            name="saldo_laudo",
        ),
    ]
