# Generated by Django 5.2.2 on 2025-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0077_remove_documentoderecebimento_saldo_laudo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoderecebimento",
            name="quantidade_laudo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantidade do laudo com 2 casas decimais",
                max_digits=15,
                null=True,
            ),
        ),
    ]
