# Generated by Django 5.2.2 on 2025-12-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0078_alter_documentoderecebimento_quantidade_laudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="programa",
            field=models.CharField(
                choices=[
                    ("LEVE_LEITE", "Leve Leite"),
                    ("ALIMENTACAO_ESCOLAR", "Alimentação Escolar"),
                ],
                default="ALIMENTACAO_ESCOLAR",
                max_length=20,
                verbose_name="Programa",
            ),
        ),
    ]
