# Generated by Django 5.2.2 on 2026-01-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0079_fichatecnicadoproduto_programa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="componentes_produto",
            field=models.CharField(
                blank=True, max_length=1500, verbose_name="Componentes do Produto"
            ),
        ),
    ]
