# Generated by Django 5.2.2 on 2026-01-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0080_alter_fichatecnicadoproduto_componentes_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichatecnicadoproduto",
            name="agroecologico",
        ),
    ]
