# Generated by Django 5.2.2 on 2026-01-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0080_interrupcaoprogramadaentrega"),
        ("pre_recebimento", "0081_remove_fichatecnicadoproduto_agroecologico"),
    ]

    operations = []
