# Generated by Django 5.2.2 on 2026-02-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0082_merge_20260128_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interrupcaoprogramadaentrega",
            name="data",
            field=models.DateField(verbose_name="Data da Interrupção"),
        ),
        migrations.AlterField(
            model_name="interrupcaoprogramadaentrega",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("EMENDA", "Emenda"),
                    ("REUNIAO", "Reunião"),
                    ("INVENTARIO", "Inventário"),
                    ("FERIADO", "Feriado"),
                    ("OUTROS", "Outros"),
                ],
                max_length=20,
                verbose_name="Motivo da Interrupção",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interrupcaoprogramadaentrega",
            unique_together={("data", "tipo_calendario")},
        ),
    ]
