# Generated by Django 5.2.2 on 2026-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0084_fichatecnicadoproduto_especie_variedade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cronograma",
            name="numero_empenho",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Número do Empenho"
            ),
        ),
        migrations.AddField(
            model_name="cronograma",
            name="qtd_total_empenho",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Qtde. Total do Empenho"
            ),
        ),
    ]
