# Generated by Django 5.2.2 on 2026-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0085_cronograma_numero_empenho_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="componentes_produto",
            field=models.TextField(blank=True, verbose_name="Componentes do Produto"),
        ),
    ]
