# Generated by Django 5.2.2 on 2026-03-30 14:06

import uuid

import django.db.models.deletion
import django_xworkflows.models
from django.db import migrations, models

import src.dados_comuns.behaviors


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0086_alter_fichatecnicadoproduto_componentes_produto"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronogramaSemanal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    django_xworkflows.models.StateField(
                        max_length=16,
                        workflow=django_xworkflows.models._SerializedWorkflow(
                            initial_state="RASCUNHO",
                            name="CronogramaSemanalWorkflow",
                            states=["RASCUNHO"],
                        ),
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cronograma_mensal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cronogramas_semanais",
                        to="pre_recebimento.cronograma",
                        verbose_name="Cronograma Mensal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma Semanal",
                "verbose_name_plural": "Cronogramas Semanais",
            },
            bases=(
                src.dados_comuns.behaviors.TemIdentificadorExternoAmigavel,
                src.dados_comuns.behaviors.Logs,
                django_xworkflows.models.BaseWorkflowEnabled,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ProgramacaoEntregaSemanal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mes_programado",
                    models.CharField(
                        help_text="Formato MM/YYYY",
                        max_length=7,
                        verbose_name="Mês Programado",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                ("data_fim", models.DateField(verbose_name="Data Fim")),
                ("quantidade", models.FloatField(verbose_name="Quantidade da Entrega")),
                (
                    "cronograma_semanal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programacoes",
                        to="pre_recebimento.cronogramasemanal",
                        verbose_name="Cronograma Semanal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programação de Entrega Semanal",
                "verbose_name_plural": "Programações de Entrega Semanal",
                "ordering": ["mes_programado", "data_inicio"],
            },
        ),
    ]
