# Generated by Django 5.2.13 on 2026-04-14 16:16

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0087_cronogramasemanal_programacaoentregasemanal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronogramasemanal",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=22,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="RASCUNHO",
                    name="CronogramaSemanalWorkflow",
                    states=["RASCUNHO", "ENVIADO_AO_FORNECEDOR"],
                ),
            ),
        ),
    ]
