# Generated by Django 5.2.13 on 2026-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0090_alter_cronogramasemanal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemdotipodeembalagem",
            name="nome",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
