# Generated by Django 5.2.17 on 2026-10-01 15:35

import django_xworkflows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0091_alter_imagemdotipodeembalagem_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoderecebimento",
            name="justificativa_reprovacao",
            field=models.TextField(
                blank=True, verbose_name="Justificativa da Reprovação"
            ),
        ),
        migrations.AlterField(
            model_name="documentoderecebimento",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=21,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="DOCUMENTO_CRIADO",
                    name="DocumentoDeRecebimentoWorkflow",
                    states=[
                        "DOCUMENTO_CRIADO",
                        "ENVIADO_PARA_ANALISE",
                        "ENVIADO_PARA_CORRECAO",
                        "APROVADO",
                        "REPROVADO",
                    ],
                ),
            ),
        ),
    ]
