# Generated by Django 4.2.7 on 2025-01-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "cardapio",
            "0047_alter_dataintervaloalteracaocardapio_cancelado_justificativa_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="suspensaoalimentacao",
            name="cancelado",
            field=models.BooleanField(default=False, verbose_name="Esta cancelado?"),
        ),
        migrations.AddField(
            model_name="suspensaoalimentacao",
            name="cancelado_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelado em"
            ),
        ),
        migrations.AddField(
            model_name="suspensaoalimentacao",
            name="cancelado_justificativa",
            field=models.CharField(
                blank=True,
                max_length=1500,
                verbose_name="Porque foi cancelado individualmente",
            ),
        ),
        migrations.AddField(
            model_name="suspensaoalimentacao",
            name="cancelado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
