# Generated by Django 5.2.2 on 2025-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0049_alter_inversaocardapio_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faixaetariasubstituicaoalimentacaocei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faixaetariasubstituicaoalimentacaocemeicei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="substituicaoalimentacaonoperiodoescolarcemeiemei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
