# Generated by Django 5.2.15 on 2026-08-05 15:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pre_recebimento", "0091_alter_imagemdotipodeembalagem_nome"),
        ("terceirizada", "0024_contrato_programa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermoRecebimentoDefinitivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "valor_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Valor do Contrato",
                    ),
                ),
                (
                    "quantidade_total_recebida",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Quantidade Total Recebida",
                    ),
                ),
                ("texto_termo", models.TextField(verbose_name="Texto do Termo")),
                (
                    "status",
                    models.CharField(
                        choices=[("RASCUNHO", "Rascunho"), ("ENVIADO", "Enviado")],
                        default="RASCUNHO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="termos_recebimento_definitivo_alterados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termos_recebimento_definitivo",
                        to="terceirizada.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cronogramas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="termos_recebimento_definitivo",
                        to="pre_recebimento.cronograma",
                        verbose_name="Cronogramas",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termos_recebimento_definitivo",
                        to="terceirizada.terceirizada",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "fiscal_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termos_recebimento_definitivo_fiscal_1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fiscal 1",
                    ),
                ),
                (
                    "fiscal_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termos_recebimento_definitivo_fiscal_2",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fiscal 2",
                    ),
                ),
                (
                    "fiscal_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termos_recebimento_definitivo_fiscal_3",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fiscal 3",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termo de Recebimento Definitivo",
                "verbose_name_plural": "Termos de Recebimento Definitivo",
            },
        ),
    ]
