# Generated by Django 5.2.15 on 2026-08-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_recebimento", "0001_initial"),
        ("pre_recebimento", "0091_alter_imagemdotipodeembalagem_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termorecebimentodefinitivo",
            name="quantidade_total_recebida",
        ),
        migrations.RemoveField(
            model_name="termorecebimentodefinitivo",
            name="valor_contrato",
        ),
        migrations.RemoveField(
            model_name="termorecebimentodefinitivo",
            name="cronogramas",
        ),
        migrations.CreateModel(
            name="CronogramaTermoRecebimentoDefinitivo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Valor do Contrato",
                    ),
                ),
                (
                    "quantidade_total_recebida",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Quantidade Total Recebida",
                    ),
                ),
                (
                    "cronograma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pre_recebimento.cronograma",
                        verbose_name="Cronograma",
                    ),
                ),
                (
                    "termo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronogramas_termo",
                        to="pos_recebimento.termorecebimentodefinitivo",
                        verbose_name="Termo de Recebimento Definitivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma do Termo de Recebimento Definitivo",
                "verbose_name_plural": "Cronogramas do Termo de Recebimento Definitivo",
                "unique_together": {("termo", "cronograma")},
            },
        ),
        migrations.AddField(
            model_name="termorecebimentodefinitivo",
            name="cronogramas",
            field=models.ManyToManyField(
                blank=True,
                related_name="termos_recebimento_definitivo",
                through="pos_recebimento.CronogramaTermoRecebimentoDefinitivo",
                to="pre_recebimento.cronograma",
                verbose_name="Cronogramas",
            ),
        ),
    ]
