# Generated by Django 5.2.13 on 2026-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pos_recebimento",
            "0002_remove_termorecebimentodefinitivo_quantidade_total_recebida_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="termorecebimentodefinitivo",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("ENVIADO_FISCAIS", "Enviado Fiscais"),
                ],
                default="RASCUNHO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
