# Generated by Django 5.2.13 on 2026-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_recebimento", "0003_alter_termorecebimentodefinitivo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termorecebimentodefinitivo",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("ENVIADO_FISCAIS", "Enviado Fiscais"),
                    ("ENVIADO_DILOG", "Enviado DILOG"),
                    ("ENVIADO_COORDENADOR", "Enviado Coordenador"),
                    ("ENVIADO_FORNECEDOR", "Enviado Fornecedor"),
                    ("ASSINADO_FORNECEDOR", "Assinado Fornecedor"),
                ],
                default="RASCUNHO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
