# Generated by Django 5.2.13 on 2026-08-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos_recebimento", "0004_alter_termorecebimentodefinitivo_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cronogramatermorecebimentodefinitivo",
            name="valor_contrato",
        ),
        migrations.AddField(
            model_name="termorecebimentodefinitivo",
            name="valor_contrato",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Valor do Contrato",
            ),
        ),
    ]
