from src.dados_comuns.constants import TIPO_UNIDADE_CEI_DIRET, TIPOS_UNIDADE_ESCOLAR

ETAPA_INFANTIL = 10


# Relatório do Historico de Dietas Autorizadas
UNIDADES_CEI = [
    TIPO_UNIDADE_CEI_DIRET,
    TIPOS_UNIDADE_ESCOLAR.CEU_CEI.value,
    TIPOS_UNIDADE_ESCOLAR.CEI.value,
    TIPOS_UNIDADE_ESCOLAR.CCI.value,
    TIPOS_UNIDADE_ESCOLAR.CCI_CIPS.value,
    TIPOS_UNIDADE_ESCOLAR.CEI_CEU.value,
]

UNIDADES_CEMEI = [
    TIPOS_UNIDADE_ESCOLAR.CEMEI.value,
    TIPOS_UNIDADE_ESCOLAR.CEU_CEMEI.value,
]

UNIDADES_EMEI_EMEF_CIEJA = [
    TIPOS_UNIDADE_ESCOLAR.EMEI.value,
    TIPOS_UNIDADE_ESCOLAR.CEU_EMEI.value,
    TIPOS_UNIDADE_ESCOLAR.EMEF.value,
    TIPOS_UNIDADE_ESCOLAR.CEU_EMEF.value,
    TIPOS_UNIDADE_ESCOLAR.EMEFM.value,
    TIPOS_UNIDADE_ESCOLAR.CIEJA.value,
    TIPOS_UNIDADE_ESCOLAR.EMEF_P_FOM.value,
    TIPOS_UNIDADE_ESCOLAR.EMEI_P_FOM.value,
]
UNIDADES_EMEBS = [TIPOS_UNIDADE_ESCOLAR.EMEBS.value]
UNIDADES_SEM_PERIODOS = [
    TIPOS_UNIDADE_ESCOLAR.CMCT.value,
    TIPOS_UNIDADE_ESCOLAR.CEU_GESTAO.value,
]
