# Generated by Django 5.2.8 on 2025-11-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dieta_especial",
            "0061_solicitacaodietaespecial_dieta_para_recreio_ferias_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitacaodietaespecial",
            name="periodo_recreio_fim",
        ),
        migrations.RemoveField(
            model_name="solicitacaodietaespecial",
            name="periodo_recreio_inicio",
        ),
    ]
