# Generated by Django 5.2.8 on 2025-12-01 11:07

from django.db import migrations, models


def inativa_polo(apps, _):
    MotivoAlteracaoUE = apps.get_model("dieta_especial", "MotivoAlteracaoUE")
    MotivoAlteracaoUE.objects.filter(nome__icontains="Polo").update(ativo=False)
    MotivoAlteracaoUE.objects.update_or_create(
        nome="Dieta Especial - Outro",
    )


def backwards(apps, _):
    MotivoAlteracaoUE = apps.get_model("dieta_especial", "MotivoAlteracaoUE")
    MotivoAlteracaoUE.objects.filter(
        nome="Dieta Especial - Outro",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "dieta_especial",
            "0062_remove_solicitacaodietaespecial_periodo_recreio_fim_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="motivoalteracaoue",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Está ativo?"),
        ),
        migrations.RunPython(inativa_polo, backwards),
    ]
