# Generated by Django 5.2.2 on 2025-12-18 14:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dieta_especial", "0063_motivoalteracaoue_ativo"),
        ("escola", "0077_diacalendario_periodo_escolar"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogQuantidadeDietasAutorizadasRecreioNasFerias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "classificacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_dietas_autorizadas_recreio_ferias",
                        to="dieta_especial.classificacaodieta",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_dietas_autorizadas_recreio_ferias",
                        to="escola.escola",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log da quantidade de dietas autorizadas por unidade escolar - Recreio nas Férias",
                "verbose_name_plural": "Logs da quantidade de dietas autorizadas por unidade escolar - Recreio nas Férias",
                "ordering": ("-data", "escola__nome"),
            },
        ),
        migrations.CreateModel(
            name="LogQuantidadeDietasAutorizadasRecreioNasFeriasCEI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "classificacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_dietas_autorizadas_recreio_ferias_cei",
                        to="dieta_especial.classificacaodieta",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_dietas_autorizadas_recreio_ferias_cei",
                        to="escola.escola",
                    ),
                ),
                (
                    "faixa_etaria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="logs_dietas_autorizadas_recreio_ferias_cei",
                        to="escola.faixaetaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log da quantidade de dietas autorizadas por unidade escolar CEI - Recreio nas Férias",
                "verbose_name_plural": "Logs da quantidade de dietas autorizadas por unidade escolar CEI - Recreio nas Férias",
                "ordering": ("-data", "escola__nome"),
            },
        ),
    ]
