# Generated by Django 5.2.12 on 2026-03-17 13:24

import django_xworkflows.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dieta_especial",
            "0064_logquantidadedietasautorizadasrecreionasferias_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaodietaespecial",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=37,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="RASCUNHO",
                    name="DietaEspecialWorkflow",
                    states=[
                        "RASCUNHO",
                        "CODAE_A_AUTORIZAR",
                        "CODAE_NEGOU_PEDIDO",
                        "CODAE_AUTORIZADO",
                        "TERCEIRIZADA_TOMOU_CIENCIA",
                        "ESCOLA_CANCELOU",
                        "CODAE_NEGOU_CANCELAMENTO",
                        "ESCOLA_SOLICITOU_INATIVACAO",
                        "CODAE_NEGOU_INATIVACAO",
                        "CODAE_AUTORIZOU_INATIVACAO",
                        "TERCEIRIZADA_TOMOU_CIENCIA_INATIVACAO",
                        "TERMINADA_AUTOMATICAMENTE_SISTEMA",
                        "CANCELADO_ALUNO_MUDOU_ESCOLA",
                        "CANCELADO_ALUNO_NAO_PERTENCE_REDE",
                        "CANCELADO_ENCERRAMENTO_MATRICULA",
                    ],
                ),
            ),
        ),
    ]
