# Generated by Django 5.2.13 on 2026-04-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dieta_especial", "0067_delete_alimentoproprio"),
        ("escola", "0080_remove_escola_tipos_contagem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipoContagem",
        ),
    ]
