# Generated by Django 5.2.2 on 2025-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0046_parametrizacaofinanceira_data_final_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametrizacaofinanceira",
            name="tipos_unidades",
        ),
    ]
