# Generated by Django 5.2.8 on 2025-11-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0046_alter_medicao_status_and_more"),
        ("medicao_inicial", "0047_remove_parametrizacaofinanceira_tipos_unidades"),
    ]

    operations = []
