# Generated by Django 5.2.2 on 2025-11-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cardapio",
            "0050_alter_faixaetariasubstituicaoalimentacaocei_matriculados_quando_criado_and_more",
        ),
        ("escola", "0076_auto_20251017_1652"),
        ("medicao_inicial", "0047_remove_parametrizacaofinanceira_tipos_unidades"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parametrizacaofinanceiratabela",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="nome_campo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="tipo_valor",
            field=models.CharField(
                choices=[
                    ("UNITARIO", "Unitário"),
                    ("REAJUSTE", "Reajuste"),
                    ("ACRESCIMO", "Acréscimo"),
                ],
                default="UNITARIO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="valor",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AlterField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="faixa_etaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametrizacao_valor_faixa_etaria",
                to="escola.faixaetaria",
            ),
        ),
        migrations.AlterField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="tipo_alimentacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametrizacao_valor_tipo_alimentacao",
                to="cardapio.tipoalimentacao",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parametrizacaofinanceiratabelavalor",
            unique_together={("tabela", "nome_campo", "tipo_valor")},
        ),
        migrations.AddField(
            model_name="parametrizacaofinanceiratabela",
            name="periodo_escolar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parametrizacao_financeira_tabela_periodo_escolar",
                to="escola.periodoescolar",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parametrizacaofinanceiratabela",
            unique_together={("nome", "parametrizacao_financeira", "periodo_escolar")},
        ),
        migrations.RemoveField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="valor_colunas",
        ),
    ]
