# Generated by Django 5.2.2 on 2025-11-10 11:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cardapio",
            "0050_alter_faixaetariasubstituicaoalimentacaocei_matriculados_quando_criado_and_more",
        ),
        ("escola", "0076_auto_20251017_1652"),
        ("medicao_inicial", "0048_merge_20251107_1625"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaAlimentacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Categoria de Alimentação",
                "verbose_name_plural": "Categorias de Alimentação",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="RecreioNasFerias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecreioNasFeriasUnidadeParticipante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("num_inscritos", models.PositiveIntegerField(default=0)),
                ("num_colaboradores", models.PositiveIntegerField(default=0)),
                ("liberar_medicao", models.BooleanField(default=False)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="escola.lote"
                    ),
                ),
                (
                    "recreio_nas_ferias",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_participantes",
                        to="medicao_inicial.recreionasferias",
                    ),
                ),
                (
                    "unidade_educacional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="escola.escola"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecreioNasFeriasUnidadeTipoAlimentacao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medicao_inicial.categoriaalimentacao",
                    ),
                ),
                (
                    "recreio_ferias_unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_alimentacao",
                        to="medicao_inicial.recreionasferiasunidadeparticipante",
                    ),
                ),
                (
                    "tipo_alimentacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cardapio.tipoalimentacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Alimentação da Unidade",
                "verbose_name_plural": "Tipos de Alimentação das Unidades",
                "unique_together": {
                    ("recreio_ferias_unidade", "tipo_alimentacao", "categoria")
                },
            },
        ),
    ]
