# Generated by Django 5.2.2 on 2025-11-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0049_tipovalorparametrizacaofinanceira_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametrizacaofinanceiratabelavalor",
            name="nome_campo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
