# Generated by Django 5.2.2 on 2025-11-10 11:40

from django.db import migrations


def criar_categorias(apps, schema_editor):
    CategoriaAlimentacao = apps.get_model("medicao_inicial", "CategoriaAlimentacao")

    categorias = ["Inscritos", "Colaboradores", "Infantil"]

    for nome in categorias:
        CategoriaAlimentacao.objects.get_or_create(nome=nome)


def reverter_categorias(apps, schema_editor):
    CategoriaAlimentacao = apps.get_model("medicao_inicial", "CategoriaAlimentacao")
    CategoriaAlimentacao.objects.filter(
        nome__in=["Inscritos", "Colaboradores", "Infantil"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0049_categoriaalimentacao_recreionasferias_and_more"),
    ]

    operations = [
        migrations.RunPython(criar_categorias, reverter_categorias),
    ]
