# Generated by Django 5.2.2 on 2025-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0050_populate_categorias_alimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="recreionasferiasunidadeparticipante",
            name="cei_ou_emei",
            field=models.CharField(
                choices=[("N/A", "N/A"), ("CEI", "CEI"), ("EMEI", "EMEI")],
                default="N/A",
                max_length=4,
            ),
        ),
    ]
