# Generated by Django 5.2.2 on 2025-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0052_merge_20251112_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrenciamedicaoinicial",
            name="nome_ultimo_arquivo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ocorrenciamedicaoinicial",
            name="ultimo_arquivo",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
