# Generated by Django 5.2.8 on 2025-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0053_alter_ocorrenciamedicaoinicial_nome_ultimo_arquivo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrenciamedicaoinicial",
            name="nome_ultimo_arquivo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
