# Generated by Django 5.2.8 on 2025-12-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0076_auto_20251017_1652"),
        ("medicao_inicial", "0055_alter_recreionasferias_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="solicitacaomedicaoinicial",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="recreio_nas_ferias",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitacoes_medicao_inicial",
                to="medicao_inicial.recreionasferias",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="solicitacaomedicaoinicial",
            unique_together={("escola", "mes", "ano", "recreio_nas_ferias")},
        ),
    ]
