# Generated by Django 5.2.9 on 2025-12-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0056_alter_solicitacaomedicaoinicial_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recreionasferias",
            options={
                "ordering": ["-alterado_em"],
                "verbose_name": "Recreio nas Férias",
                "verbose_name_plural": "Recreios nas Férias",
            },
        ),
        migrations.AlterModelOptions(
            name="recreionasferiasunidadeparticipante",
            options={
                "verbose_name": "Recreio nas Férias - Unidade Participante",
                "verbose_name_plural": "Recreios nas Férias - Unidades Participantes",
            },
        ),
    ]
