# Generated by Django 5.2.2 on 2025-12-16 11:11

from django.db import migrations


def inserir_grupos_medicao(apps, schema_editor):
    GrupoMedicao = apps.get_model("medicao_inicial", "GrupoMedicao")

    nomes = [
        "Recreio nas Férias",
        "Recreio nas Férias - de 0 a 3 anos e 11 meses",
        "Recreio nas Férias - 4 a 14 anos",
        "Colaboradores",
    ]

    for nome in nomes:
        GrupoMedicao.objects.get_or_create(
            nome=nome,
            defaults={"ativo": True},
        )


def remover_grupos_medicao(apps, schema_editor):
    GrupoMedicao = apps.get_model("medicao_inicial", "GrupoMedicao")

    GrupoMedicao.objects.filter(
        nome__in=[
            "Recreio nas Férias",
            "Recreio nas Férias - de 0 a 3 anos e 11 meses",
            "Recreio nas Férias - 4 a 14 anos",
            "Colaboradores",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0057_alter_recreionasferias_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            inserir_grupos_medicao,
            remover_grupos_medicao,
        ),
    ]
