# Generated by Django 5.2.12 on 2026-03-17 08:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0060_lancheemergencialdiario"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancheemergencialdiario",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Criado em"
            ),
        ),
        migrations.AddField(
            model_name="lancheemergencialdiario",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="lancheemergencialdiario",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
