# Generated by Django 5.2.13 on 2026-05-07 14:41

from django.conf import settings
from django.db import migrations, models


def check_no_duplicate_sem_recreio(apps, schema_editor):
    SolicitacaoMedicaoInicial = apps.get_model("medicao_inicial", "SolicitacaoMedicaoInicial")
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT escola_id, mes, ano, COUNT(*) as cnt
            FROM medicao_inicial_solicitacaomedicaoinicial
            WHERE recreio_nas_ferias_id IS NULL
            GROUP BY escola_id, mes, ano
            HAVING COUNT(*) > 1
        """)
        duplicates = cursor.fetchall()
    if duplicates:
        details = "; ".join(
            f"escola_id={row[0]}, mes={row[1]}, ano={row[2]} ({row[3]} duplicatas)"
            for row in duplicates
        )
        raise Exception(
            f"Existem solicitações duplicadas sem recreio que precisam ser removidas antes "
            f"de aplicar esta migration. Duplicatas encontradas: {details}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0080_remove_escola_tipos_contagem"),
        ("medicao_inicial", "0064_alter_relatoriofinanceiro_status"),
        ("terceirizada", "0024_contrato_programa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_no_duplicate_sem_recreio, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="solicitacaomedicaoinicial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recreio_nas_ferias__isnull", True)),
                fields=("escola", "mes", "ano"),
                name="unique_solicitacao_sem_recreio",
            ),
        ),
    ]
