# Generated by Django 5.2.14 on 2026-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0065_solicitacaomedicaoinicial_unique_solicitacao_sem_recreio",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsavel",
            name="rf",
            field=models.CharField(max_length=11),
        ),
    ]
