# Generated by Django 5.2.13 on 2026-06-23 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0082_alter_alunoperiodoparcial_unique_together"),
        ("medicao_inicial", "0066_alter_responsavel_rf"),
    ]

    operations = [
        migrations.CreateModel(
            name="DescontoFinanceiro",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "tipo_lancamento",
                    models.CharField(
                        choices=[
                            ("ALIMENTACOES", "Alimentações"),
                            ("DIETA_TIPO_A", "Dieta Especial grupo A"),
                            ("DIETA_TIPO_B", "Dieta Especial grupo B"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de lançamento",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(verbose_name="Quantidade")),
                (
                    "clausula_desconto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dados_desconto_financeiro",
                        to="medicao_inicial.clausuladedesconto",
                    ),
                ),
                (
                    "faixa_etaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dados_desconto_financeiro",
                        to="escola.faixaetaria",
                    ),
                ),
                (
                    "periodo_escolar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dados_desconto_financeiro",
                        to="escola.periodoescolar",
                    ),
                ),
                (
                    "relatorio_financeiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dados_desconto_financeiro",
                        to="medicao_inicial.relatoriofinanceiro",
                        to_field="uuid",
                    ),
                ),
                (
                    "unidades_educacionais",
                    models.ManyToManyField(
                        related_name="dados_desconto_financeiro", to="escola.escola"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dado de desconto financeiro",
                "verbose_name_plural": "Dados de desconto financeiro",
                "ordering": ["-alterado_em"],
            },
        ),
    ]
