# Generated by Django 5.2.13 on 2026-06-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0067_descontofinanceiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="tipo_lancamento",
            field=models.CharField(
                choices=[
                    ("ALIMENTACOES", "Alimentação"),
                    ("DIETAS_TIPO_A", "Dieta Especial Tipo A"),
                    ("DIETAS_TIPO_B", "Dieta Especial Tipo B"),
                ],
                max_length=30,
                verbose_name="Tipo de lançamento",
            ),
        ),
    ]
