# Generated by Django 5.2.13 on 2026-06-25 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0055_remove_suspensao_alimentacao_no_periodo_escolar"),
        ("escola", "0083_dialetivosigpae"),
        ("medicao_inicial", "0068_alter_descontofinanceiro_tipo_lancamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="descontofinanceiro",
            name="tipo_alimentacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descontos_financeiros",
                to="cardapio.tipoalimentacao",
            ),
        ),
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="clausula_desconto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descontos_financeiros",
                to="medicao_inicial.clausuladedesconto",
            ),
        ),
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="faixa_etaria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descontos_financeiros",
                to="escola.faixaetaria",
            ),
        ),
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="periodo_escolar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descontos_financeiros",
                to="escola.periodoescolar",
            ),
        ),
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="relatorio_financeiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="descontos_financeiros",
                to="medicao_inicial.relatoriofinanceiro",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="unidades_educacionais",
            field=models.ManyToManyField(
                related_name="descontos_financeiros", to="escola.escola"
            ),
        ),
    ]
