# Generated by Django 5.2.14 on 2026-06-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0069_descontofinanceiro_tipo_alimentacao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="descontofinanceiro",
            options={
                "ordering": ["-alterado_em"],
                "verbose_name": "Desconto Financeiro",
                "verbose_name_plural": "Descontos Financeiros",
            },
        ),
    ]
