# Generated by Django 5.2.14 on 2026-07-03

from django.db import migrations, models


def verifica_ausencia_de_medicoes_duplicadas(apps, schema_editor):
    from django.db import connection

    # 1) periodo-type: solic_medicao_inicial + periodo_escolar (grupo IS NULL)
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT solicitacao_medicao_inicial_id, periodo_escolar_id, COUNT(*) AS cnt
            FROM medicao_inicial_medicao
            WHERE grupo_id IS NULL AND periodo_escolar_id IS NOT NULL
            GROUP BY solicitacao_medicao_inicial_id, periodo_escolar_id
            HAVING COUNT(*) > 1
        """)
        duplicates_periodo = cursor.fetchall()

    # 2) grupo-type: solic_medicao_inicial + grupo (periodo_escolar IS NULL)
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT solicitacao_medicao_inicial_id, grupo_id, COUNT(*) AS cnt
            FROM medicao_inicial_medicao
            WHERE grupo_id IS NOT NULL AND periodo_escolar_id IS NULL
            GROUP BY solicitacao_medicao_inicial_id, grupo_id
            HAVING COUNT(*) > 1
        """)
        duplicates_grupo = cursor.fetchall()

    # 3) ambos preenchidos: solic_medicao_inicial + periodo_escolar + grupo
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT solicitacao_medicao_inicial_id, periodo_escolar_id, grupo_id, COUNT(*) AS cnt
            FROM medicao_inicial_medicao
            WHERE grupo_id IS NOT NULL AND periodo_escolar_id IS NOT NULL
            GROUP BY solicitacao_medicao_inicial_id, periodo_escolar_id, grupo_id
            HAVING COUNT(*) > 1
        """)
        duplicates_ambos = cursor.fetchall()

    errors = []
    if duplicates_periodo:
        details = "; ".join(
            f"sol_medicao_inicial_id={row[0]}, periodo_escolar_id={row[1]} ({row[2]} duplicatas)"
            for row in duplicates_periodo
        )
        errors.append(f"Duplicatas de periodo: {details}")
    if duplicates_grupo:
        details = "; ".join(
            f"sol_medicao_inicial_id={row[0]}, grupo_id={row[1]} ({row[2]} duplicatas)"
            for row in duplicates_grupo
        )
        errors.append(f"Duplicatas de grupo: {details}")
    if duplicates_ambos:
        details = "; ".join(
            f"sol_medicao_inicial_id={row[0]}, periodo_escolar_id={row[1]}, grupo_id={row[2]} ({row[3]} duplicatas)"
            for row in duplicates_ambos
        )
        errors.append(f"Duplicatas de periodo+grupo: {details}")

    if errors:
        raise Exception(
            "Existem Medicoes duplicadas que precisam ser removidas antes de aplicar esta migration. "
            + " | ".join(errors)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0080_remove_escola_tipos_contagem"),
        ("medicao_inicial", "0070_alter_descontofinanceiro_options"),
    ]

    operations = [
        migrations.RunPython(
            verifica_ausencia_de_medicoes_duplicadas, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name="medicao",
            constraint=models.UniqueConstraint(
                fields=["solicitacao_medicao_inicial", "periodo_escolar"],
                condition=models.Q(("grupo__isnull", True)),
                name="unique_medicao_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicao",
            constraint=models.UniqueConstraint(
                fields=["solicitacao_medicao_inicial", "grupo"],
                condition=models.Q(("periodo_escolar__isnull", True)),
                name="unique_medicao_grupo",
            ),
        ),
        migrations.AddConstraint(
            model_name="medicao",
            constraint=models.UniqueConstraint(
                fields=["solicitacao_medicao_inicial", "periodo_escolar", "grupo"],
                condition=models.Q(
                    ("periodo_escolar__isnull", False),
                    ("grupo__isnull", False),
                ),
                name="unique_medicao_periodo_grupo",
            ),
        ),
    ]
