# Generated by Django 5.2.14 on 2026-07-06 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0083_dialetivosigpae"),
        ("medicao_inicial", "0071_medicao_unique_constraints"),
        ("terceirizada", "0024_contrato_programa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="medicao",
            name="unique_medicao_periodo_grupo",
        ),
        migrations.AddConstraint(
            model_name="medicao",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("grupo__isnull", False), ("periodo_escolar__isnull", False)
                ),
                fields=("solicitacao_medicao_inicial", "periodo_escolar", "grupo"),
                name="unique_medicao_periodo_grupo",
            ),
        ),
    ]
