# Generated by Django 5.2.15 on 2026-08-03 10:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


def cria_tipos_sobremesa_doce(apps, schema_editor):
    TipoSobremesaDoce = apps.get_model("medicao_inicial", "TipoSobremesaDoce")
    TipoSobremesaDoce.objects.get_or_create(nome="Sobremesa Doce")
    TipoSobremesaDoce.objects.get_or_create(nome="Sobremesa AF")


def reverte_tipos_sobremesa_doce(apps, schema_editor):
    TipoSobremesaDoce = apps.get_model("medicao_inicial", "TipoSobremesaDoce")
    DiaSobremesaDoce = apps.get_model("medicao_inicial", "DiaSobremesaDoce")
    DiaSobremesaDoce.objects.all().update(tipo=None)
    TipoSobremesaDoce.objects.filter(
        nome__in=["Sobremesa Doce", "Sobremesa AF"]
    ).delete()


def vincula_tipo_a_dias_sobremesa(apps, schema_editor):
    TipoSobremesaDoce = apps.get_model("medicao_inicial", "TipoSobremesaDoce")
    DiaSobremesaDoce = apps.get_model("medicao_inicial", "DiaSobremesaDoce")
    tipo_sobremesa_doce = TipoSobremesaDoce.objects.get(nome="Sobremesa Doce")
    DiaSobremesaDoce.objects.all().update(tipo=tipo_sobremesa_doce)


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0072_remove_medicao_unique_medicao_periodo_grupo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoSobremesaDoce",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(blank=True, max_length=100, verbose_name="Nome"),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Está ativo?"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Sobremesa Doce",
                "verbose_name_plural": "Tipos de Sobremesa Doce",
            },
        ),
        migrations.AddField(
            model_name="diasobremesadoce",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="medicao_inicial.tiposobremesadoce",
            ),
        ),
        migrations.RunPython(
            cria_tipos_sobremesa_doce, reverse_code=reverte_tipos_sobremesa_doce
        ),
        migrations.RunPython(
            vincula_tipo_a_dias_sobremesa, reverse_code=migrations.RunPython.noop
        ),
    ]
