# Generated by Django 5.2.13 on 2026-08-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0072_remove_medicao_unique_medicao_periodo_grupo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="descontofinanceiro",
            name="cei_ou_emei",
            field=models.CharField(
                choices=[("N/A", "N/A"), ("CEI", "CEI"), ("EMEI", "EMEI")],
                default="N/A",
                max_length=4,
            ),
        ),
    ]
