# Generated by Django 5.2.15 on 2026-08-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0084_alter_escola_acesso_desde"),
        ("medicao_inicial", "0073_tiposobremesadoce_diasobremesadoce_tipo"),
        ("terceirizada", "0024_contrato_programa"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="diasobremesadoce",
            unique_together={("tipo_unidade", "data", "edital", "tipo")},
        ),
    ]
