# Generated by Django 5.2.13 on 2026-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0075_descontofinanceiro_cei_ou_emei"),
    ]

    operations = [
        migrations.AddField(
            model_name="descontofinanceiro",
            name="infantil_ou_fundamental",
            field=models.CharField(
                choices=[
                    ("N/A", "N/A"),
                    ("INFANTIL", "INFANTIL"),
                    ("FUNDAMENTAL", "FUNDAMENTAL"),
                ],
                default="N/A",
                max_length=11,
            ),
        ),
    ]
