# Generated by Django 5.2.13 on 2026-08-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0076_descontofinanceiro_infantil_ou_fundamental"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadosliquidacao",
            name="relatorio_financeiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dados_liquidacao",
                to="medicao_inicial.relatoriofinanceiro",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="descontofinanceiro",
            name="relatorio_financeiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="descontos_financeiros",
                to="medicao_inicial.relatoriofinanceiro",
                to_field="uuid",
            ),
        ),
    ]
