# Generated by Django 5.2.13 on 2026-09-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0077_alter_dadosliquidacao_relatorio_financeiro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="descricao_metodo",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Descrição do método de contagem",
            ),
        ),
    ]
