# Generated by Django 5.2.17 on 2026-09-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicao_inicial", "0078_solicitacaomedicaoinicial_descricao_metodo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empenho",
            name="contrato",
        ),
        migrations.RemoveField(
            model_name="empenho",
            name="edital",
        ),
        migrations.DeleteModel(
            name="DadosLiquidacao",
        ),
        migrations.DeleteModel(
            name="Empenho",
        ),
    ]
