# Generated by Django 5.2.17 on 2026-10-06 09:09

from django.db import migrations, models

NOME_GRUPO_MEDICAO = "Solicitações de Alimentação Extraordinárias"


def inserir_grupo_medicao(apps, schema_editor):
    GrupoMedicao = apps.get_model("medicao_inicial", "GrupoMedicao")

    GrupoMedicao.objects.get_or_create(
        nome=NOME_GRUPO_MEDICAO,
        defaults={"ativo": True},
    )


def remover_grupo_medicao(apps, schema_editor):
    GrupoMedicao = apps.get_model("medicao_inicial", "GrupoMedicao")

    GrupoMedicao.objects.filter(nome=NOME_GRUPO_MEDICAO).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicao_inicial",
            "0079_remove_empenho_contrato_remove_empenho_edital_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaomedicaoinicial",
            name="lanche_emergencial_extraordinario",
            field=models.BooleanField(
                default=False,
                help_text="Solicita a correção do apontamento de Lanche Emergencial em datas excepcionalmente autorizadas pela CODAE.",
                verbose_name="Lanche Emergencial Extraordinário",
            ),
        ),
        migrations.RunPython(
            inserir_grupo_medicao,
            remover_grupo_medicao,
        ),
    ]
