# Generated by Django 5.2.2 on 2025-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kit_lanche", "0023_alter_escolaquantidade_cancelado_justificativa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faixaetariasolicitacaokitlancheceiavulsa",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faixasquantidadeskitlancheceidacemei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitacaokitlancheemeidacemei",
            name="matriculados_quando_criado",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
