# Generated by Django 5.2.2 on 2025-11-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terceirizada", "0023_alter_contrato_modalidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="programa",
            field=models.CharField(
                choices=[
                    ("LEVE_LEITE", "Leve Leite"),
                    ("ALIMENTACAO_ESCOLAR", "Alimentação Escolar"),
                ],
                default="ALIMENTACAO_ESCOLAR",
                max_length=20,
                verbose_name="Programa",
            ),
        ),
    ]
