# Generated by Django 4.2.7 on 2025-02-19 14:27

import django_xworkflows.models
from django.db import connection, migrations


def altera_status_assinado_dinutre_para_assinado_dilog_abastecimento(
    apps, schema_editor
):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pre_recebimento_cronograma
            SET status = 'ASSINADO_DILOG_ABASTECIMENTO'
            WHERE status = 'ASSINADO_DINUTRE'
            """
        )


def altera_status_assinado_dilog_abastecimento_para_assinado_dinutre(
    apps, schema_editor
):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pre_recebimento_cronograma
            SET status = 'ASSINADO_DINUTRE'
            WHERE status = 'ASSINADO_DILOG_ABASTECIMENTO'
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0060_alter_fichatecnicadoproduto_porcao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronograma",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=32,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="RASCUNHO",
                    name="CronogramaWorkflow",
                    states=[
                        "RASCUNHO",
                        "ASSINADO_E_ENVIADO_AO_FORNECEDOR",
                        "ALTERACAO_CODAE",
                        "ASSINADO_FORNECEDOR",
                        "SOLICITADO_ALTERACAO",
                        "ASSINADO_DILOG_ABASTECIMENTO",
                        "ASSINADO_CODAE",
                    ],
                ),
            ),
        ),
        migrations.RunPython(
            altera_status_assinado_dinutre_para_assinado_dilog_abastecimento,
            reverse_code=altera_status_assinado_dilog_abastecimento_para_assinado_dinutre,
        ),
    ]
