# Generated by Django 4.2.7 on 2025-02-20 09:43

import django_xworkflows.models
from django.db import connection, migrations


def altera_status_dinutre_para_dilog_abastecimento(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pre_recebimento_solicitacaoalteracaocronograma
            SET status = 'APROVADO_DILOG_ABASTECIMENTO'
            WHERE status = 'APROVADO_DINUTRE'
            """
        )
        cursor.execute(
            """
            UPDATE pre_recebimento_solicitacaoalteracaocronograma
            SET status = 'REPROVADO_DILOG_ABASTECIMENTO'
            WHERE status = 'REPROVADO_DINUTRE'
            """
        )


def altera_status_dilog_abastecimento_para_dinutre(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pre_recebimento_solicitacaoalteracaocronograma
            SET status = 'APROVADO_DINUTRE'
            WHERE status = 'APROVADO_DILOG_ABASTECIMENTO'
            """
        )
        cursor.execute(
            """
            UPDATE pre_recebimento_solicitacaoalteracaocronograma
            SET status = 'REPROVADO_DINUTRE'
            WHERE status = 'REPROVADO_DILOG_ABASTECIMENTO'
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0061_alter_cronograma_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaoalteracaocronograma",
            name="status",
            field=django_xworkflows.models.StateField(
                max_length=29,
                workflow=django_xworkflows.models._SerializedWorkflow(
                    initial_state="SOLICITACAO_CRIADA",
                    name="CronogramaAlteracaoWorkflow",
                    states=[
                        "SOLICITACAO_CRIADA",
                        "EM_ANALISE",
                        "ALTERACAO_ENVIADA_FORNECEDOR",
                        "FORNECEDOR_CIENTE",
                        "CRONOGRAMA_CIENTE",
                        "APROVADO_DILOG_ABASTECIMENTO",
                        "REPROVADO_DILOG_ABASTECIMENTO",
                        "APROVADO_DILOG",
                        "REPROVADO_DILOG",
                    ],
                ),
            ),
        ),
        migrations.RunPython(
            altera_status_dinutre_para_dilog_abastecimento,
            reverse_code=altera_status_dilog_abastecimento_para_dinutre,
        ),
    ]
