# Generated by Django 4.2.7 on 2025-04-02 13:52

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0062_alter_solicitacaoalteracaocronograma_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etapasdocronograma",
            options={
                "ordering": (
                    models.Case(
                        models.When(
                            etapa__gt="",
                            etapa__isnull=False,
                            then=django.db.models.functions.comparison.Cast(
                                django.db.models.functions.text.Substr(
                                    models.F("etapa"), models.Value(7)
                                ),
                                models.IntegerField(),
                            ),
                        ),
                        default=models.Value(0),
                        output_field=models.IntegerField(),
                    ),
                    "parte",
                    "data_programada",
                ),
                "verbose_name": "Etapa do Cronograma",
                "verbose_name_plural": "Etapas dos Cronogramas",
            },
        ),
    ]
