# Generated by Django 4.2.7 on 2025-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0063_alter_etapasdocronograma_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cronograma",
            name="numero",
            field=models.CharField(
                blank=True,
                max_length=250,
                unique=True,
                verbose_name="Número do Cronograma",
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="complemento_fabricante",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="habilitacao",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Habilitação"
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="nome_responsavel_tecnico",
            field=models.CharField(
                blank=True,
                max_length=250,
                verbose_name="Nome completo do Responsável Técnico",
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="numero",
            field=models.CharField(
                blank=True,
                max_length=250,
                unique=True,
                verbose_name="Número da Ficha Técnica",
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="numero_registro_orgao",
            field=models.CharField(
                blank=True,
                max_length=250,
                verbose_name="Nº do Registro em Órgão Competente",
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="prazo_validade_descongelamento",
            field=models.CharField(
                blank=True,
                help_text="Prazo de Validade após o descongelamento e mantido sob refrigeração",
                max_length=250,
                verbose_name="Prazo de Validade Descongelamento",
            ),
        ),
    ]
