# Generated by Django 5.2 on 2025-05-14 10:49

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0065_alter_etapasdocronograma_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etapasdocronograma",
            options={
                "ordering": (
                    models.OrderBy(
                        django.db.models.functions.comparison.Cast(
                            django.db.models.functions.text.Substr(
                                models.F("etapa"), models.Value(7)
                            ),
                            models.IntegerField(),
                        )
                    ),
                    "parte",
                    "data_programada",
                ),
                "verbose_name": "Etapa do Cronograma",
                "verbose_name_plural": "Etapas dos Cronogramas",
            },
        ),
    ]
