# Generated by Django 5.2 on 2025-06-02

from django.db import migrations, models


def migrate_etapa_forward(apps, schema_editor):
    """Migrate data from etapa to etapa_new, extracting the number from 'Etapa X'."""

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pre_recebimento_etapasdocronograma
            SET etapa_new = CAST(SUBSTRING(etapa FROM 'Etapa (\\d+)') AS INTEGER)
            WHERE etapa ~ '^Etapa \\d+$';
        """
        )

        cursor.execute(
            """
            UPDATE pre_recebimento_etapasdocronograma
            SET etapa_new = NULL
            WHERE etapa IS NULL OR etapa = '' OR etapa !~ '^Etapa \\d+$';
        """
        )


def migrate_etapa_backward(apps, schema_editor):
    """Migrate data back from etapa_new to etapa, converting to 'Etapa X' format."""

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE pre_recebimento_etapasdocronograma
            SET etapa = 'Etapa ' || etapa_new::text
            WHERE etapa_new IS NOT NULL;
        """
        )

        cursor.execute(
            """
            UPDATE pre_recebimento_etapasdocronograma
           SET etapa = ''
            WHERE etapa_new IS NULL;
        """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0065_alter_etapasdocronograma_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapasdocronograma",
            name="etapa_new",
            field=models.IntegerField(blank=True, null=True, verbose_name="Etapa"),
        ),
        migrations.RunPython(
            code=migrate_etapa_forward,
            reverse_code=migrate_etapa_backward,
        ),
        migrations.AlterField(
            model_name="etapasdocronograma",
            name="etapa",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
