# Generated by Django 5.2.1 on 2025-06-16 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pre_recebimento", "0067_rename_etapa_new_and_remove_etapa_old"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="etapasdocronograma",
            options={
                "verbose_name": "Etapa do Cronograma",
                "verbose_name_plural": "Etapas dos Cronogramas",
            },
        ),
    ]
