# Generated by Django 5.2.2 on 2025-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0075_alter_etapasdocronograma_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentoderecebimento",
            name="quantidade_laudo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentoderecebimento",
            name="saldo_laudo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
