# Generated by Django 5.2.2 on 2026-01-21 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0079_fichatecnicadoproduto_programa"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterrupcaoProgramadaEntrega",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Alterado em"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data",
                    models.DateField(unique=True, verbose_name="Data da Interrupção"),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("EMENDA", "Emenda"),
                            ("REUNIAO", "Reunião"),
                            ("INVENTARIO", "Inventário"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Motivo da Interrupção",
                    ),
                ),
                (
                    "descricao_motivo",
                    models.TextField(
                        blank=True,
                        help_text="Obrigatório quando motivo = OUTROS",
                        verbose_name="Descrição do Motivo",
                    ),
                ),
                (
                    "tipo_calendario",
                    models.CharField(
                        choices=[
                            ("ARMAZENAVEL", "Armazenável"),
                            ("PONTO_A_PONTO", "Ponto a Ponto"),
                        ],
                        default="ARMAZENAVEL",
                        max_length=20,
                        verbose_name="Tipo de Calendário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interrupção Programada de Entrega",
                "verbose_name_plural": "Interrupções Programadas de Entregas",
            },
        ),
    ]
