# Generated by Django 5.2.2 on 2026-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pre_recebimento", "0083_alter_interrupcaoprogramadaentrega_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="especie_variedade",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Espécie ou Variedade Cultivada",
            ),
        ),
        migrations.AddField(
            model_name="fichatecnicadoproduto",
            name="tipo_entrega",
            field=models.CharField(
                choices=[("ARMAZEM", "Armazém"), ("PONTO_A_PONTO", "Ponto a Ponto")],
                default="ARMAZEM",
                max_length=20,
                verbose_name="Tipo de Entrega",
            ),
        ),
        migrations.AlterField(
            model_name="fichatecnicadoproduto",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERECIVEIS", "Perecíveis"),
                    ("NAO_PERECIVEIS", "Não Perecíveis"),
                    ("FLV", "FLV"),
                ],
                max_length=14,
            ),
        ),
    ]
