name: CI/CD Pip (cache)
 
on:
  schedule:
    - cron: "10 5 * * *"
  workflow_dispatch:

jobs:
     
  cache:
  
    runs-on: self-hosted
    steps:          
      - name: Ajustando HOME para o cache
        run: |
           cd $RUNNER_WORKSPACE
           cd ..
           pwd
           echo "GITHUB_RUN_HOME=$(pwd)" >> $GITHUB_ENV
      - name: Show envs..
        run: echo $GITHUB_RUN_HOME
          
      - name: Cache Pipenv virtualenv
        uses: actions/cache@v3
        id: pipenv-cache
        with:
          path: ${{ env.GITHUB_RUN_HOME }}/_temp/_github_home/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      - name: Running Python Tests
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        uses: prefeiturasp/SME-GithubAction-Images@python38-v1.0
        with:
          command: |
            pip install --user pipenv pipenv==2022.4.8
            pipenv install --dev
