name: Dev - CI/CD
 
on:

  push:
    branches: [ development ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:
         
  build:

    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - uses: actions/checkout@v2     
      -  name: Login to registry
         uses: docker/login-action@v2
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}
    
      - name: Build the Docker image    
        run: | 
             docker build . --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-sigpae-api
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-sigpae-api
             
  deploy:
  
    runs-on: self-hosted
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/development' }}        
    environment:
      name: development
    steps:
      - name: Redeploy
        uses: luizhpriotto/action_images@kubectl-sigpae-v1.0
        env: 
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          NAMESPACE: sme-sigpae-dev
